fail_fast: true
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.2.0
    hooks:
    -   id: check-yaml
    -   id: end-of-file-fixer
    -   id: trailing-whitespace
-   repo: https://github.com/psf/black
    rev: 22.3.0
    hooks:
    -   id: black-jupyter
-   repo: https://github.com/fastai/nbdev
    rev: 2.3.4
    hooks:
    -   id: nbdev_clean
    -   id: nbdev_export
