repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
    -   id: check-yaml
-   repo: https://github.com/fastai/nbdev
    rev: 2.3.4
    hooks:
    -   id: nbdev_clean
    -   id: nbdev_export
