# Autogenerated by nbdev

d = {
    "settings": {
        "branch": "master",
        "doc_baseurl": "/poniard",
        "doc_host": "https://rxavier.github.io",
        "git_url": "https://github.com/rxavier/poniard",
        "lib_path": "poniard",
    },
    "syms": {
        "poniard.estimators.classification": {},
        "poniard.estimators.core": {
            "poniard.estimators.core.PoniardBaseEstimator": (
                "core.html#poniardbaseestimator",
                "poniard/estimators/core.py",
            ),
            "poniard.estimators.core.PoniardBaseEstimator.__add__": (
                "core.html#__add__",
                "poniard/estimators/core.py",
            ),
            "poniard.estimators.core.PoniardBaseEstimator.__getitem__": (
                "core.html#__getitem__",
                "poniard/estimators/core.py",
            ),
            "poniard.estimators.core.PoniardBaseEstimator.__init__": (
                "core.html#__init__",
                "poniard/estimators/core.py",
            ),
            "poniard.estimators.core.PoniardBaseEstimator.__repr__": (
                "core.html#__repr__",
                "poniard/estimators/core.py",
            ),
            "poniard.estimators.core.PoniardBaseEstimator.__sub__": (
                "core.html#__sub__",
                "poniard/estimators/core.py",
            ),
            "poniard.estimators.core.PoniardBaseEstimator._add_dummy_estimators": (
                "core.html#_add_dummy_estimators",
                "poniard/estimators/core.py",
            ),
            "poniard.estimators.core.PoniardBaseEstimator._build_cv": (
                "core.html#_build_cv",
                "poniard/estimators/core.py",
            ),
            "poniard.estimators.core.PoniardBaseEstimator._build_metrics": (
                "core.html#_build_metrics",
                "poniard/estimators/core.py",
            ),
            "poniard.estimators.core.PoniardBaseEstimator._build_pipelines": (
                "core.html#_build_pipelines",
                "poniard/estimators/core.py",
            ),
            "poniard.estimators.core.PoniardBaseEstimator._build_preprocessor": (
                "core.html#_build_preprocessor",
                "poniard/estimators/core.py",
            ),
            "poniard.estimators.core.PoniardBaseEstimator._default_estimators": (
                "core.html#_default_estimators",
                "poniard/estimators/core.py",
            ),
            "poniard.estimators.core.PoniardBaseEstimator._first_scorer": (
                "core.html#_first_scorer",
                "poniard/estimators/core.py",
            ),
            "poniard.estimators.core.PoniardBaseEstimator._infer_dtypes": (
                "core.html#_infer_dtypes",
                "poniard/estimators/core.py",
            ),
            "poniard.estimators.core.PoniardBaseEstimator._init_plots": (
                "core.html#_init_plots",
                "poniard/estimators/core.py",
            ),
            "poniard.estimators.core.PoniardBaseEstimator._init_plugins": (
                "core.html#_init_plugins",
                "poniard/estimators/core.py",
            ),
            "poniard.estimators.core.PoniardBaseEstimator._pass_instance_attrs": (
                "core.html#_pass_instance_attrs",
                "poniard/estimators/core.py",
            ),
            "poniard.estimators.core.PoniardBaseEstimator._predict": (
                "core.html#_predict",
                "poniard/estimators/core.py",
            ),
            "poniard.estimators.core.PoniardBaseEstimator._process_long_results": (
                "core.html#_process_long_results",
                "poniard/estimators/core.py",
            ),
            "poniard.estimators.core.PoniardBaseEstimator._process_results": (
                "core.html#_process_results",
                "poniard/estimators/core.py",
            ),
            "poniard.estimators.core.PoniardBaseEstimator._run_plugin_method": (
                "core.html#_run_plugin_method",
                "poniard/estimators/core.py",
            ),
            "poniard.estimators.core.PoniardBaseEstimator._train_test_split_from_cv": (
                "core.html#_train_test_split_from_cv",
                "poniard/estimators/core.py",
            ),
            "poniard.estimators.core.PoniardBaseEstimator.add_estimators": (
                "core.html#add_estimators",
                "poniard/estimators/core.py",
            ),
            "poniard.estimators.core.PoniardBaseEstimator.add_preprocessing_step": (
                "core.html#add_preprocessing_step",
                "poniard/estimators/core.py",
            ),
            "poniard.estimators.core.PoniardBaseEstimator.build_ensemble": (
                "core.html#build_ensemble",
                "poniard/estimators/core.py",
            ),
            "poniard.estimators.core.PoniardBaseEstimator.cv_": (
                "core.html#cv_",
                "poniard/estimators/core.py",
            ),
            "poniard.estimators.core.PoniardBaseEstimator.decision_function": (
                "core.html#decision_function",
                "poniard/estimators/core.py",
            ),
            "poniard.estimators.core.PoniardBaseEstimator.estimators_": (
                "core.html#estimators_",
                "poniard/estimators/core.py",
            ),
            "poniard.estimators.core.PoniardBaseEstimator.fit": (
                "core.html#fit",
                "poniard/estimators/core.py",
            ),
            "poniard.estimators.core.PoniardBaseEstimator.get_estimator": (
                "core.html#get_estimator",
                "poniard/estimators/core.py",
            ),
            "poniard.estimators.core.PoniardBaseEstimator.get_predictions_similarity": (
                "core.html#get_predictions_similarity",
                "poniard/estimators/core.py",
            ),
            "poniard.estimators.core.PoniardBaseEstimator.get_results": (
                "core.html#get_results",
                "poniard/estimators/core.py",
            ),
            "poniard.estimators.core.PoniardBaseEstimator.metrics_": (
                "core.html#metrics_",
                "poniard/estimators/core.py",
            ),
            "poniard.estimators.core.PoniardBaseEstimator.poniard_task": (
                "core.html#poniard_task",
                "poniard/estimators/core.py",
            ),
            "poniard.estimators.core.PoniardBaseEstimator.predict": (
                "core.html#predict",
                "poniard/estimators/core.py",
            ),
            "poniard.estimators.core.PoniardBaseEstimator.predict_all": (
                "core.html#predict_all",
                "poniard/estimators/core.py",
            ),
            "poniard.estimators.core.PoniardBaseEstimator.predict_proba": (
                "core.html#predict_proba",
                "poniard/estimators/core.py",
            ),
            "poniard.estimators.core.PoniardBaseEstimator.preprocessor_": (
                "core.html#preprocessor_",
                "poniard/estimators/core.py",
            ),
            "poniard.estimators.core.PoniardBaseEstimator.reassign_types": (
                "core.html#reassign_types",
                "poniard/estimators/core.py",
            ),
            "poniard.estimators.core.PoniardBaseEstimator.remove_estimators": (
                "core.html#remove_estimators",
                "poniard/estimators/core.py",
            ),
            "poniard.estimators.core.PoniardBaseEstimator.setup": (
                "core.html#setup",
                "poniard/estimators/core.py",
            ),
            "poniard.estimators.core.PoniardBaseEstimator.show_results": (
                "core.html#show_results",
                "poniard/estimators/core.py",
            ),
            "poniard.estimators.core.PoniardBaseEstimator.tune_estimator": (
                "core.html#tune_estimator",
                "poniard/estimators/core.py",
            ),
        },
        "poniard.estimators.regression": {},
        "poniard.plot.plot_factory": {},
        "poniard.plugins.core": {},
        "poniard.plugins.pandas_profiling": {},
        "poniard.plugins.wandb": {},
        "poniard.preprocessing.categorical": {},
        "poniard.preprocessing.datetime": {},
        "poniard.utils.estimate": {},
        "poniard.utils.hyperparameters": {},
        "poniard.utils.stats": {},
    },
}
