project:
  type: website

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

website:
  twitter-card: true
  open-graph: true
  repo-actions: [issue]
  navbar:
    background: primary
    search: true
  sidebar:
    style: floating
    search: true
    contents:
      - index.ipynb
      - section: Guide
        contents: guide/*.ipynb
      - section: Reference
        contents:
          - estimators.core.ipynb
          - estimators.classifier.ipynb
          - estimators.regressor.ipynb
          - plotting.ipynb
          - plugins.ipynb

metadata-files: [nbdev.yml]