name: Test conda

on:
  - push
  - pull_request

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.7', '3.8', '3.9', '3.10']

    steps:
    - uses: actions/checkout@v1
    - name: Setup conda
      uses: s-weigand/setup-conda@v1
      with:
        update-conda: true
        python-version: ${{ matrix.python-version }}
        conda-channels: anaconda, conda-forge
    - run: conda --version
    - run: which python

    - name: Install dependencies
      run: |
        conda install -c conda-forge tox tox-conda pytest
        python -m pip install tox tox-gh-actions pytest
    - name: Test with tox
      run: tox
