name: CI
on:  [workflow_dispatch, pull_request, push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: nbdev
        uses: fastai/workflows/nbdev-ci@master
        with:
          pre: true
