name: Test

on: [workflow_dispatch, pull_request, push]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]
        python-version: ['3.7', '3.8', '3.9', '3.10']

    steps:
    - uses: actions/checkout@v1
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install tox tox-gh-actions pytest

    - name: Test with tox
      run: tox

  test_nbdev:
    runs-on: ubuntu-latest
    steps: [uses: fastai/workflows/nbdev-ci@master]

  publish:
    if: startsWith(github.ref, 'refs/tags')
    needs: build
    uses: rxavier/poniard/.github/workflows/publish.yml@main
    secrets:
      PYPI_API_TOKEN: ${{ secrets.PYPI_API_TOKEN }}
